### ISSUE TITLE
Executing op HashTableV2 in device /job:localhost/replica:0/task:0/device:CPU:0

### ISSUE THREAD

**Issue by hippocampus24** [wgwang/ccks2020-baseline#1]
**运行一次这段的时候报错！**
**entities_by_third_party_tool = aug_entities_by_third_party_tool()
for ent_type, ents in entities_by_third_party_tool.items():
    to_be_trained_entities[ent_type] = list(set(to_be_trained_entities[ent_type] + ents))**

Executing op HashTableV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip. See stack trace below
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/layers/transformers/loader.py", line 101, in build_transformer
    assert len(vocab) == 1, 'No vocab found or unambiguous vocabs found'
AssertionError: No vocab found or unambiguous vocabs found
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.42. Try to upgrade hanlp with
pip install --upgrade hanlp
If the problem persists, please submit an issue to https://github.com/hankcs/HanLP/issues .
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 48, in load_from_meta_file
    obj.load(save_dir, **load_kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 244, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/common/component.py", line 255, in build
    loss=kwargs.get('loss', None)))
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/components/taggers/transformers/transformer_tagger.py", line 36, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/layers/transformers/loader.py", line 101, in build_transformer
    assert len(vocab) == 1, 'No vocab found or unambiguous vocabs found'
AssertionError: No vocab found or unambiguous vocabs found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-6828a2bdfc43>", line 2, in <module>
    entities_by_third_party_tool = aug_entities_by_third_party_tool()
  File "<ipython-input-8-e9ee8fd91bfe>", line 2, in aug_entities_by_third_party_tool
    hanlpner = HanlpNER()
  File "<ipython-input-7-a77c0e1e4faa>", line 4, in __init__
    self.recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/__init__.py", line 51, in load
    return load_from_meta_file(save_dir, meta_filename, transform_only=transform_only, load_kwargs=load_kwargs, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/hanlp/utils/component_util.py", line 64, in load_from_meta_file
    exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1151, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/anaconda3/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
An exception has occurred, use %tb to see the full traceback.

---------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

SystemExit: 1

**Comment by wgwang** [comment]
看了下是hanlp的模型文件和版本不匹配的情况

AssertionError: No vocab found or unambiguous vocabs found
https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20200104_185735.zip was created with hanlp-2.0.0-alpha.5, while you are running 2.0.0-alpha.42. Try to upgrade hanlp with
pip install --upgrade hanlp

需要下载2.0.0-alpha.42的模型文件。或者升级hanlp试试。

**Comment by tanzf** [comment]
下载2.0.0-alpha.42的模型文件，去那下载，能给个下载链接吗？谢谢
